using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AtlasNOC.Infrastructure.Persistence.Migrations;

public partial class AddOperationalCore : Migration
{
    protected override void Up(MigrationBuilder m)
    {
        m.CreateTable("Customers", t => new { Id = t.Column<Guid>(nullable:false), ServiceCode=t.Column<string>(maxLength:64,nullable:false), Name=t.Column<string>(maxLength:200,nullable:false), Phone=t.Column<string>(maxLength:64), Email=t.Column<string>(maxLength:255), Status=t.Column<int>(nullable:false), CreatedAtUtc=t.Column<DateTime>(nullable:false) }, c=>{ c.PrimaryKey("PK_Customers",x=>x.Id); c.UniqueConstraint("AK_Customers_ServiceCode",x=>x.ServiceCode); });
        m.CreateTable("ServicePlans", t => new { Id=t.Column<Guid>(nullable:false), Name=t.Column<string>(maxLength:200,nullable:false), MonthlyPrice=t.Column<decimal>(type:"decimal(18,2)",nullable:false), DownloadMbps=t.Column<int>(nullable:false), UploadMbps=t.Column<int>(nullable:false), IsActive=t.Column<bool>(nullable:false) }, c=>c.PrimaryKey("PK_ServicePlans",x=>x.Id));
        m.CreateTable("CustomerServices", t => new { Id=t.Column<Guid>(nullable:false), CustomerId=t.Column<Guid>(nullable:false), PlanId=t.Column<Guid>(nullable:false), ServiceAddress=t.Column<string>(maxLength:500,nullable:false), Status=t.Column<int>(nullable:false), ActivatedAtUtc=t.Column<DateTime>(nullable:true) }, c=>{ c.PrimaryKey("PK_CustomerServices",x=>x.Id); c.ForeignKey("FK_CustomerServices_Customers",x=>x.CustomerId,"Customers","Id",onDelete:ReferentialAction.Cascade); c.ForeignKey("FK_CustomerServices_ServicePlans",x=>x.PlanId,"ServicePlans","Id",onDelete:ReferentialAction.Restrict); });
        m.CreateTable("BillingAccounts", t => new { Id=t.Column<Guid>(nullable:false), CustomerId=t.Column<Guid>(nullable:false), Balance=t.Column<decimal>(type:"decimal(18,2)",nullable:false) }, c=>{ c.PrimaryKey("PK_BillingAccounts",x=>x.Id); c.ForeignKey("FK_BillingAccounts_Customers",x=>x.CustomerId,"Customers","Id",onDelete:ReferentialAction.Cascade); c.UniqueConstraint("AK_BillingAccounts_CustomerId",x=>x.CustomerId); });
        m.CreateTable("BillingEntries", t => new { Id=t.Column<Guid>(nullable:false), AccountId=t.Column<Guid>(nullable:false), Type=t.Column<int>(nullable:false), Amount=t.Column<decimal>(type:"decimal(18,2)",nullable:false), Description=t.Column<string>(maxLength:500,nullable:false), OccurredAtUtc=t.Column<DateTime>(nullable:false) }, c=>{ c.PrimaryKey("PK_BillingEntries",x=>x.Id); c.ForeignKey("FK_BillingEntries_BillingAccounts",x=>x.AccountId,"BillingAccounts","Id",onDelete:ReferentialAction.Cascade); });
        m.CreateTable("SupportTickets", t => new { Id=t.Column<Guid>(nullable:false), CustomerId=t.Column<Guid>(nullable:false), Title=t.Column<string>(maxLength:300,nullable:false), Description=t.Column<string>(maxLength:4000), Status=t.Column<int>(nullable:false), CreatedAtUtc=t.Column<DateTime>(nullable:false) }, c=>{ c.PrimaryKey("PK_SupportTickets",x=>x.Id); c.ForeignKey("FK_SupportTickets_Customers",x=>x.CustomerId,"Customers","Id",onDelete:ReferentialAction.Restrict); });
        m.CreateTable("InventoryAssets", t => new { Id=t.Column<Guid>(nullable:false), AssetTag=t.Column<string>(maxLength:100,nullable:false), SerialNumber=t.Column<string>(maxLength:200), MacAddress=t.Column<string>(maxLength:32), Type=t.Column<string>(maxLength:100,nullable:false), Status=t.Column<int>(nullable:false), CustomerServiceId=t.Column<Guid>(nullable:true) }, c=>{ c.PrimaryKey("PK_InventoryAssets",x=>x.Id); c.ForeignKey("FK_InventoryAssets_CustomerServices",x=>x.CustomerServiceId,"CustomerServices","Id",onDelete:ReferentialAction.SetNull); });
        m.CreateTable("CoverageChecks", t => new { Id=t.Column<Guid>(nullable:false), Address=t.Column<string>(maxLength:500,nullable:false), Status=t.Column<int>(nullable:false), CapacityMbps=t.Column<int>(nullable:true), CheckedAtUtc=t.Column<DateTime>(nullable:false) }, c=>c.PrimaryKey("PK_CoverageChecks",x=>x.Id));
        m.CreateTable("TechnicianVisits", t => new { Id=t.Column<Guid>(nullable:false), CustomerId=t.Column<Guid>(nullable:false), ScheduledAtUtc=t.Column<DateTime>(nullable:false), WorkType=t.Column<string>(maxLength:200,nullable:false), EstimatedMinutes=t.Column<int>(nullable:false) }, c=>{ c.PrimaryKey("PK_TechnicianVisits",x=>x.Id); c.ForeignKey("FK_TechnicianVisits_Customers",x=>x.CustomerId,"Customers","Id",onDelete:ReferentialAction.Restrict); });
        m.CreateIndex("IX_Customers_Name", "Customers", "Name"); m.CreateIndex("IX_CustomerServices_CustomerId", "CustomerServices", "CustomerId"); m.CreateIndex("IX_BillingEntries_AccountId_OccurredAtUtc", "BillingEntries", new[]{"AccountId","OccurredAtUtc"}); m.CreateIndex("IX_SupportTickets_Status", "SupportTickets", "Status"); m.CreateIndex("IX_InventoryAssets_SerialNumber", "InventoryAssets", "SerialNumber"); m.CreateIndex("IX_TechnicianVisits_ScheduledAtUtc", "TechnicianVisits", "ScheduledAtUtc");
    }
    protected override void Down(MigrationBuilder m)
    { m.DropTable("TechnicianVisits"); m.DropTable("CoverageChecks"); m.DropTable("InventoryAssets"); m.DropTable("SupportTickets"); m.DropTable("BillingEntries"); m.DropTable("BillingAccounts"); m.DropTable("CustomerServices"); m.DropTable("ServicePlans"); m.DropTable("Customers"); }
}
